# Generated by Django 4.1.7 on 2023-07-10 09:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='', max_length=200)),
                ('organization', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('admin_auth_user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vbs_travel_client',
            },
        ),
        migrations.CreateModel(
            name='TravelPackagesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(default='', max_length=200)),
                ('stage', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='open', max_length=200)),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('total_vendor_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('first_installment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('second_installment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('third_installment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('less_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('no_of_days', models.IntegerField(default=0)),
                ('passport_no', models.CharField(default='', max_length=200)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_status', models.BooleanField(default=False, max_length=10)),
                ('tentative_payment_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 14, 44, 29, 721542), null=True)),
                ('arrival_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 14, 44, 29, 721542), null=True)),
                ('departure_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 14, 44, 29, 721542), null=True)),
                ('destination', models.CharField(default='', max_length=200)),
                ('boarding', models.CharField(default='', max_length=200)),
                ('package_type', models.CharField(default='', max_length=200)),
                ('quantity_of_packages', models.CharField(default='', max_length=200)),
                ('package_name', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'travel_packages_application',
            },
        ),
        migrations.CreateModel(
            name='VBSEmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_employee_id', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('employee_auth_user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vbs_employee_details',
            },
        ),
        migrations.CreateModel(
            name='TravelVisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(default='', max_length=200)),
                ('passport_no', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('visiting_country', models.CharField(default='', max_length=200)),
                ('stage', models.CharField(default='detail processing', max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('invoice_status', models.BooleanField(default=False)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cgst_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sgst_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vbs_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('express_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('authority_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visa_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('sub_location', models.CharField(default='', max_length=200)),
                ('handover_date', models.DateTimeField(blank=True, null=True)),
                ('courier_in_date', models.DateTimeField(blank=True, null=True)),
                ('courier_out_date', models.DateTimeField(blank=True, null=True)),
                ('document_collection_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
                ('travel_client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient')),
            ],
            options={
                'db_table': 'travel_visa_application',
            },
        ),
        migrations.CreateModel(
            name='TravelTicketsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=200)),
                ('client_name', models.CharField(default='', max_length=200)),
                ('applicants_name', models.CharField(default='', max_length=200)),
                ('stage', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='open', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('trip_type', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('invoice_status', models.BooleanField(default=False, max_length=10)),
                ('origin', models.CharField(default='', max_length=200)),
                ('destination', models.CharField(default='', max_length=200)),
                ('via', models.CharField(default='', max_length=200)),
                ('mode_of_transport', models.CharField(default='', max_length=200)),
                ('vehicle_no', models.CharField(default='', max_length=200)),
                ('travel_class', models.CharField(default='', max_length=200)),
                ('gds_pnr_no', models.CharField(default='', max_length=200)),
                ('airline_pnr_no', models.CharField(default='', max_length=200)),
                ('departure_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 14, 44, 29, 722051), null=True)),
                ('arrival_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 14, 44, 29, 722051), null=True)),
                ('base_fees', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('service_fees', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('issued_from', models.CharField(default='', max_length=200)),
                ('agent_ref', models.CharField(default='', max_length=200)),
                ('employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
                ('travel_client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient')),
            ],
            options={
                'db_table': 'travel_tickets_application',
            },
        ),
        migrations.CreateModel(
            name='TravelPackagesVendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('vendor_payment_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_payment_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_payment_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('less_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('package_appl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelpackagesapplication')),
            ],
            options={
                'db_table': 'travel_packages_vendor_payment',
            },
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='employee_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails'),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='travel_client_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient'),
        ),
        migrations.CreateModel(
            name='TravelApplicationControlTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_agent_id', models.CharField(default='', max_length=200)),
                ('appl_id', models.CharField(default='', max_length=200)),
                ('is_transfer_revoked', models.BooleanField(default=False, max_length=10)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('previous_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'travel_appl_control_transfer',
            },
        ),
        migrations.CreateModel(
            name='FollowUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_id', models.CharField(default='', max_length=200)),
                ('application_type', models.CharField(default='', max_length=200)),
                ('followup_stage', models.CharField(default='', max_length=200)),
                ('time_for_followups', models.DateTimeField(default=datetime.datetime.now)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'followups',
            },
        ),
    ]
