# Generated by Django 4.1.7 on 2023-07-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='first_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='less_taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='second_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='third_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='total_vendor_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='vendor_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
