# Generated by Django 4.1.7 on 2023-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelpackagesapplication_first_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
