# Generated by Django 4.1.7 on 2023-07-20 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travelvisaapplication_visa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelfollowups',
            name='contact_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='travelfollowups',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 35, 34, 657162), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 35, 34, 657162), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 35, 34, 657162), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 35, 34, 657162), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 10, 35, 34, 657162), null=True),
        ),
    ]
