# Generated by Django 4.1.7 on 2023-06-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelclient_admin_auth_user_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackagesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_days', models.IntegerField(default=0)),
                ('passport_no', models.CharField(default='', max_length=200)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_status', models.BooleanField(default=False, max_length=10)),
                ('tentative_payment_date', models.DateTimeField(blank=True)),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('departure_date', models.DateTimeField(blank=True)),
                ('destination', models.CharField(default='', max_length=200)),
                ('boarding', models.CharField(default='', max_length=200)),
                ('package_type', models.CharField(default='', max_length=200)),
                ('quantity_of_packages', models.CharField(default='', max_length=200)),
                ('package_name', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'travel_packages_application',
            },
        ),
        migrations.AlterField(
            model_name='travelclient',
            name='client_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelclient',
            name='contact_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelclient',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='TravelVisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants_name', models.CharField(default='', max_length=200)),
                ('passport_no', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('visiting_country', models.CharField(default='', max_length=200)),
                ('invoice_status', models.BooleanField(default=False, max_length=10)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vbs_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('express_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('authority_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('visa_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('sub_location', models.CharField(default='', max_length=200)),
                ('handover_date', models.DateTimeField(blank=True)),
                ('courier_in_date', models.DateTimeField(blank=True)),
                ('courier_out_date', models.DateTimeField(blank=True)),
                ('document_collection_date', models.DateTimeField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
                ('travel_client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient')),
            ],
            options={
                'db_table': 'travel_visa_application',
            },
        ),
        migrations.CreateModel(
            name='TravelPackagesVendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_name', models.CharField(default='', max_length=200)),
                ('vendor_payment_1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_payment_2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vendor_payment_3', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('less_taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('package_appl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelpackagesapplication')),
            ],
            options={
                'db_table': 'travel_packages_vendor_payment',
            },
        ),
        migrations.AddField(
            model_name='travelpackagesapplication',
            name='travel_client_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient'),
        ),
    ]
