# Generated by Django 4.1.7 on 2023-07-20 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_travelfollowups_contact_number_travelfollowups_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelfollowups',
            name='application_status',
            field=models.CharField(default='blocked', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelfollowups',
            name='followup_stage',
            field=models.CharField(default='in_followups', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 20, 47, 15, 912366), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 20, 47, 15, 912366), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 20, 47, 15, 912366), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 20, 47, 15, 913362), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 20, 20, 47, 15, 913362), null=True),
        ),
    ]
