# Generated by Django 4.1.7 on 2023-06-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_travelpackagesapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelApplicationControlTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_agent_id', models.CharField(default='', max_length=200)),
                ('appl_id', models.CharField(default='', max_length=200)),
                ('is_transfer_revoked', models.BooleanField(default=False, max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('previous_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'travel_appl_control_transfer',
            },
        ),
        migrations.CreateModel(
            name='FollowUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_id', models.CharField(default='', max_length=200)),
                ('application_type', models.CharField(default='', max_length=200)),
                ('followup_stage', models.CharField(default='', max_length=200)),
                ('time_for_followups', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'followups',
            },
        ),
    ]
