# Generated by Django 4.1.7 on 2023-06-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_travelapplicationcontroltransfer_followups'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTicketApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='', max_length=200)),
                ('client_name', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200)),
                ('trip_type', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice_status', models.BooleanField(default=False, max_length=10)),
                ('origin', models.CharField(default='', max_length=200)),
                ('destination', models.CharField(default='', max_length=200)),
                ('via', models.CharField(default='', max_length=200)),
                ('mode_of_transport', models.CharField(default='', max_length=200)),
                ('vehicle_no', models.CharField(default='', max_length=200)),
                ('travel_class', models.CharField(default='', max_length=200)),
                ('gds_pnr_no', models.CharField(default='', max_length=200)),
                ('airline_pnr_no', models.CharField(default='', max_length=200)),
                ('departure_date', models.DateTimeField(blank=True)),
                ('arrival_date', models.DateTimeField(blank=True)),
                ('base_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('markup', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('issued_from', models.CharField(default='', max_length=200)),
                ('employee_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
                ('travel_client_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.travelclient')),
            ],
            options={
                'db_table': 'travel_tickets_application',
            },
        ),
    ]
