# Generated by Django 4.1.7 on 2023-06-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_travelticketapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelvisaapplication',
            name='courier_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelvisaapplication',
            name='courier_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelvisaapplication',
            name='document_collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelvisaapplication',
            name='handover_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
