# Generated by Django 4.1.7 on 2023-07-24 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_travelpackagesapplication_arrival_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelticketsapplication',
            old_name='net_amount',
            new_name='gross_amount',
        ),
        migrations.AddField(
            model_name='travelticketsapplication',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 24, 12, 38, 15, 439175), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 24, 12, 38, 15, 439175), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 24, 12, 38, 15, 439175), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 24, 12, 38, 15, 439175), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 24, 12, 38, 15, 439175), null=True),
        ),
    ]
