# Generated by Django 4.1.7 on 2023-07-10 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_travelpackagesapplication_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 16, 39, 50, 484442), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 16, 39, 50, 484442), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='first_installment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='gross_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='less_taxes',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='net_amount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='second_installment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='service_fees',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 16, 39, 50, 484442), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='third_installment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='total_vendor_payment',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 16, 39, 50, 484442), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 10, 16, 39, 50, 484442), null=True),
        ),
    ]
