# Generated by Django 4.1.7 on 2023-08-24 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_alter_travelpackagesapplication_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelvisaapplication',
            name='receipt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelvisaapplication',
            name='ref_num',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 10, 28, 22, 677756), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 10, 28, 22, 677756), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 10, 28, 22, 677756), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 10, 28, 22, 677756), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 24, 10, 28, 22, 677756), null=True),
        ),
    ]
