# Generated by Django 4.1.7 on 2023-08-25 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_travelvisaapplication_collection_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelvisaapplication',
            name='collection_date',
        ),
        migrations.AddField(
            model_name='travelvisaapplication',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 10, 40, 39, 647425), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 10, 40, 39, 647425), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 10, 40, 39, 647425), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 10, 40, 39, 647425), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 25, 10, 40, 39, 647425), null=True),
        ),
    ]
