# Generated by Django 4.1.7 on 2023-07-11 01:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_travelpackagesapplication_arrival_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelFollowUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appl_id', models.CharField(default='', max_length=200)),
                ('followup_stage', models.CharField(default='', max_length=200)),
                ('time_for_followups', models.TimeField()),
                ('date_for_followups', models.DateField()),
                ('remarks', models.CharField(default='', max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.vbsemployeedetails')),
            ],
            options={
                'db_table': 'travel_followups',
            },
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 44, 9, 146893), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 44, 9, 146893), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 44, 9, 146893), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 44, 9, 146893), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 44, 9, 146893), null=True),
        ),
        migrations.DeleteModel(
            name='FollowUps',
        ),
    ]
