# Generated by Django 4.1.7 on 2023-07-11 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_travelfollowups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelfollowups',
            name='application_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 56, 35, 316725), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 56, 35, 316725), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 56, 35, 316725), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 56, 35, 319770), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 11, 6, 56, 35, 319770), null=True),
        ),
    ]
