# Generated by Django 4.1.7 on 2023-08-28 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_travelvisaapplication_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelticketsapplication',
            name='entity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='travelticketsapplication',
            name='onwards',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 14, 15, 49, 93809), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 14, 15, 49, 93809), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 14, 15, 49, 93809), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 14, 15, 49, 93809), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 28, 14, 15, 49, 93809), null=True),
        ),
    ]
