# Generated by Django 4.1.7 on 2023-08-29 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_travelticketsapplication_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelticketsapplication',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelticketsapplication',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 29, 15, 24, 18, 35515), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 29, 15, 24, 18, 35515), null=True),
        ),
        migrations.AlterField(
            model_name='travelpackagesapplication',
            name='tentative_payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 29, 15, 24, 18, 35515), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 29, 15, 24, 18, 35515), null=True),
        ),
        migrations.AlterField(
            model_name='travelticketsapplication',
            name='departure_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 8, 29, 15, 24, 18, 35515), null=True),
        ),
    ]
